CREATE DATABASE IF NOT EXISTS bh1750_db;
USE bh1750_db;

CREATE TABLE IF NOT EXISTS data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE DEFAULT CURRENT_DATE,
    time TIME DEFAULT CURRENT_TIME,
    light FLOAT
)